---
- name: Install packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - libxml2-dev
    - libsnmp-dev
    - libcurl4-gnutls-dev

- name: Install MySQL
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - mysql-server      
    - libmysqlclient-dev
    - python-mysqldb    
    - php5-mysql
  when: zabbix3proxy_db_install and zabbix3proxy_db == "mysql"
