---
- name: Include OS-specifc vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specifc tasks
  include: "{{ ansible_os_family }}.yml"

- name: Configure Zabbix3
  include: zabbix3proxy.yml

- name: Configure MySQL
  include: mysql.yml
  when: zabbix3proxy_db_install and zabbix3proxy_db == "mysql"
