---
- name: Download Zabbix3
  get_url: url={{ zabbix3proxy_downloadurl }} dest=/usr/src
  register: zabbix3proxy_tar

- name: Extract Zabbix3
  unarchive: src={{ zabbix3proxy_tar.dest }} dest={{ zabbix3proxy_tar.dest | dirname }} copy=no
  args:
  # {{ zabbix3proxy_tar.dest }} is the downloaded file
  # {{ zabbix3proxy_tar.dest | dirname }} is the download dir

- name: Create group account
  group: name={{ zabbix3proxy_user }} state=present

- name: Create user account
  user: name={{ zabbix3proxy_user }} group={{ zabbix3proxy_user }} createhome=no state=present

- name: Ensure presence of install_path
  file: name={{ zabbix3proxy_install_path }} state=directory owner=root group=root mode=0751

- name: Compile
  shell: ./configure {{ zabbix3proxy_compile_options }} && make install
  args:
    chdir: "{{ zabbix3proxy_tar.dest | dirname }}/zabbix-{{ zabbix3proxy_betaversion }}"
    # goes to downloaded file extracted
    creates: "{{ zabbix3proxy_install_path }}/sbin/zabbix_proxy"
    # one file that is extracted, make idempotency

- name: Copy template zabbix_proxy.conf
  template: src=zabbix_proxy.conf.j2 dest={{ zabbix3proxy_install_path }}/etc/zabbix_proxy.conf
  notify: restart zabbix_proxy

- name: Copy zabbix_proxy service file
  template: src=zabbix_proxy_tru64_init.j2 dest=/etc/init.d/zabbix_proxy owner=root group=root mode=0700
